config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :flights

  devise_for :users

  post '/reservations/create/:id', to: 'reservations#create'
  get 'search_airport', to: 'home#showairport'

  get 'ajax_show_reservation/index'
  get '/ajax_show_reservation/:id', to: 'ajax_show_reservation#show'
  get '/reservations/delete/:id', to: 'reservations#destroy'
  get 'compte/index'
  get 'home/index'

  get 'reservations/confirmations/:id_billet', to: 'reservations#confirmation'

  get 'qr/:id', to: 'qr#index'


  root to: "home#index"
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:number, :departure_airport, :arrival_airport, :business_class_seats, :economy_class_seats, :duration, :departure_date)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>" class="flex flex-wrap my-3 mx-16 w-full h-40 border shadow rounded-md px-3 py-4 hover:scale-102 ease-linear transition-all duration-150">
  <div class="w-9/12 border-r-2 border-main flex items-center flew-row">
    <div class="w-9/12 flex flex-row justify-center">
      <div class="w-1/3 flex flex-col items-center">
        <p class="font-extrabold"><%= flight.departure_date.strftime("%H:%M") %></p>
        <p class="mt-2 text-sm text-gray-700"><%= flight.departure_airport %></p>
      </div>
      <div class="relative w-1/3 flex flex-row items-center justify-center">
        <div class="absolute w-full h-0.5 bg-gray-400 rounded"></div>
        <ion-icon class="w-6 h-6 bg-white text-main px-2" name="airplane"></ion-icon>
        <div class="absolute w-full top-full flex items-center justify-center text-sm text-gray-500">Durée <%= Time.at(flight.duration).utc.strftime("%M:%S") %></div>
      </div>
      <div class="w-1/3 flex flex-col items-center">
        <p class="font-extrabold"><%= (flight.departure_date + flight.duration.minutes).strftime("%H:%M") %></p>
        <p class="mt-2 text-sm text-gray-700"><%= flight.arrival_airport %></p>
      </div>
    </div>
    <div class="w-3/12 flex flex-col items-center justify-center">
      <p class="text-sm text-gray-500">Numéro du vol</p>
      <p class="mt-1 font-bold">AC <%= flight.number %></p>
      <p class="hidden"><%= flight.business_class_seats %></p>
      <p class="hidden"><%= flight.economy_class_seats %></p>
    </div>
  </div>
  <div class="w-3/12 flex flex-col justify-center items-center">
    <p class="mb-2 text-sm"><%= flight.departure_date.strftime("%d/%m/%Y") %></p>
    <% if user_signed_in? %>
      <button @click="isOpen = ! isOpen" onclick="voir_reservation(<%= flight.id %>)" class="border rounded bg-main/80 px-3 py-2 hover:bg-main text-white">Réserver</button>
    <% else %>
      <p class="text-sm">Pour réserver, il faut vous connecter</p>
    <% end %>
  </div>
</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :departure_airport, style: "display: block" %>
    <%= form.text_field :departure_airport %>
  </div>

  <div>
    <%= form.label :arrival_airport, style: "display: block" %>
    <%= form.text_field :arrival_airport %>
  </div>

  <div>
    <%= form.label :business_class_seats, style: "display: block" %>
    <%= form.number_field :business_class_seats %>
  </div>

  <div>
    <%= form.label :economy_class_seats, style: "display: block" %>
    <%= form.number_field :economy_class_seats %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :departure_date, style: "display: block" %>
    <%= form.datetime_field :departure_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flights</h1>

<div >
  <% @flights.each do |flight| %>
    <%= render flight %>
    <p>
      <%= link_to "Show this flight", flight %>
    </p>
  <% end %>
</div>

<%= link_to "New flight", new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<%= @random %>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to flights", flights_path %>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>