config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :flights

  devise_for :users

  post '/reservations/create/:id', to: 'reservations#create'
  get 'search_airport', to: 'home#showairport'

  get 'ajax_show_reservation/index'
  get '/ajax_show_reservation/:id', to: 'ajax_show_reservation#show'
  get '/reservations/delete/:id', to: 'reservations#destroy'
  get 'compte/index'
  get 'home/index'

  get 'reservations/confirmations/:id_billet', to: 'reservations#confirmation'

  get 'qr/:id', to: 'qr#index'


  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @flights = Flight.where('departure_date > ?', Time.now.localtime).page(params[:page]).per(10)
    #puts "Time a localtime form : #{a.localtime}\n\n"

    if user_signed_in?
      @nombre_reservations_attente = Reservation.where("user_id = :user_id AND statut = :statu", {user_id: current_user.id, statu: "en attente"}).count
    end

  end

  def showairport
    if user_signed_in?
      @nombre_reservations_attente = Reservation.where("user_id = :user_id AND statut = :statu", {user_id: current_user.id, statu: "en attente"}).count
    end

    if params[:arrival_airport] == ""
      @flights = Flight.where("departure_airport = :departure", {departure: params[:departure_airport]}).page(params[:page]).per(10)
    elsif params[:departure_airport] == ""
      @flights = Flight.where("arrival_airport = :arrival", {arrival: params[:arrival_airport]}).page(params[:page]).per(10)
    else
      @flights = Flight.where("departure_airport = :departure AND arrival_airport = :arrival", {departure: params[:departure_airport], arrival: params[:arrival_airport]}).page(params[:page]).per(10)
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if notice || alert %>
  <div class="absolute top-6 left-6 z-[99]">
    <div class="p-4 bg-green-600 rounded">
      <p class="text-sm text-white">
        <%= notice %>
        <%= alert %>
      </p>
    </div>
  </div>
<% end %>

<div x-data="{ isOpen: false }">

  <div class="w-full h-screen overflow-hidden">
    <!--<video class="w-full h-full absolute left-0 top-0 object-cover" src="video.mp4" autoplay muted loop type="mp4"></video>-->
    <img class="w-full h-full absolute left-0 top-0 object-cover" src="https://images4.alphacoders.com/241/241776.jpg">

    <%= image_tag("mask.jpg", class: "absolute w-full h-full left-0 top-0 z-1 mix-blend-screen") %>

    <div class="absolute w-full h-full flex justify-center items-center">
      <h1 class="text-[13vw] text-white uppercase font-bold text-shadow">AirCrash</h1>
    </div>

    <% if user_signed_in? %>
      <div class="absolute top-10 right-20 z-99 flex flex-row">

        <% if @nombre_reservations_attente > 0 %>
        <div x-data="{ dropdownOpen: false }" class="relative inline-block text-left">
          <div>
            <button type="button" @click="dropdownOpen = ! dropdownOpen" class="relative inline-flex justify-center w-full border-gray-300 px-2 py-2" id="menu-button" aria-expanded="true" aria-haspopup="true">
              <ion-icon class="relative w-5 h-5 text-main" name="notifications-outline">
              </ion-icon>
              <div class="absolute top-2 right-2 bg-red-500 text-sm border rounded-full w-2 h-2"></div>
              <span class="animate-ping absolute inline-flex w-5 h-5 rounded-full bg-main opacity-75"></span>
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div
            x-show="dropdownOpen"
            x-transition:enter="transition ease-out duration-100"
            x-transition:enter-start="transform opacity-0 scale-95"
            x-transition:enter-end="transform opacity-100 scale-100"
            x-transition:leave="transition ease-in duration-75"
            x-transition:leave-start="transform opacity-100 scale-100"
            x-transition:leave-end="transform opacity-0 scale-95"
            class="origin-center absolute right-0 mt-2 w-96 rounded-md shadow-lg flex justify-center items-center bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
              <p class="text-gray-700 block px-4 py-2 text-sm"><span class="font-extrabold text-main text-base mr-2"><%= @nombre_reservations_attente  %></span> réservations en attentes de confirmations</p>
          </div>
        </div>
        <% end %>
        <%= button_to 'Se déconnecter', destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white" %>
        <%= link_to 'Mes réservations', compte_index_path, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
      </div>
    <% else %>
      <div class="absolute top-10 right-20 z-99 flex flex-row">
        <%= link_to 'Se connecter', new_user_session_path, :data => { :no_turbolink => true }, :class => "text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
        <%= link_to 'S\'inscrire', new_user_registration_path, :data => { :no_turbolink => true }, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
      </div>
    <% end %>


      <div class="absolute bottom-10 left-0 w-full">
        <%= form_with :url => "search_airport", method: :get do |form| %>
          <div class="mx-32 bg-slate-100/80 shadow-md h-24 flex flex-wrap justify-center items-center px-6">
            <div class="w-2/5 flex flex-row justify-center items-center px-10">
              <p class="text-sm">Départ</p>
              <%= form.text_field :departure_airport, :class => "text-sm ml-3 border rounded bg-white px-3 py-2 outline-none w-full", :placeholder => "Aéroport Départ" %>
            </div>
            <div class="w-2/5 flex flex-row justify-center items-center px-10">
              <p class="text-sm">Arrivée</p>
              <%= form.text_field :arrival_airport, :class => "text-sm ml-3 border rounded bg-white px-3 py-2 outline-none w-full", :placeholder => "Aéroport Arrivée" %>
            </div>
            <div class="w-1/5 flex flex-col justify-center items-center">
              <%= form.submit "Rechercher", :class => "border rounded bg-main/80 px-3 py-2 hover:bg-main text-white" %>
            </div>
          </div>
        <% end %>
      </div>
  </div>

  <div class="mt-16">
    <div class="relative flex justify-center items-center flex-col">
      <div class="absolute w-11/12 h-2 bg-main z-[1] rounded"></div>
      <h2 class="text-5xl uppercase font-bold text-shadow z-[2] bg-white px-10">Liste de recherche de vols</h2>
    </div>
    <div class="mt-16 flex flex-wrap">
      <% @flights.each do |flight| %>
        <%= render flight %>
      <% end %>
    </div>

    <div class="flex mt-4 mx-16 justify-center items-center">
      <div class="flex flex-row">
        <%= paginate @flights %>
      </div>
    </div>
  </div>


  <footer class="mt-8 bg-main h-32 flex flex-wrap px-24 text-white">
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <a href="#" class="hover:text-gray-300">Conditions générales de transport</a>
      <a class="mt-1 hover:text-gray-300" href="#">Conditions d’utilisation</a>
      <a class="mt-1 hover:text-gray-300" href="#">Politique de confidentialité</a>
    </div>
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <p>2022 © DAWIN B. Tous droits réservés</p>
      <p class="uppercase text-xl font-extrabold mt-1">ra</p>
    </div>
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <a href="#" class="hover:text-gray-300">Cookies</a>
      <a class="mt-1 hover:text-gray-300" href="#">Nous contacter</a>
      <a class="mt-1 hover:text-gray-300" href="#">Préférences en matière de cookies</a>
    </div>
  </footer>

  <div
    x-show="isOpen"
    x-transition:enter="ease-out duration-100"
    x-transition:enter-start="hidden"
    x-transition:enter-end="block"
    x-transition:leave="ease-in duration-100"
    x-transition:leave-start="block"
    x-transition:leave-end="hidden"
    class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">

    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

    <div class="fixed z-10 inset-0 overflow-y-auto">
      <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
        <div
          class="bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-lg sm:w-full">
          <%= form_with :html=> {:id => 'url_form'}, method: :post do |form| %>
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
              <div class="py-3 flex flex-row justify-center">
                <div class="w-1/3 flex flex-col items-center">
                  <p class="font-extrabold" id="heure_depart"></p>
                  <p class="mt-1 text-sm text-gray-700" id="air_depart"></p>
                </div>
                <div class="relative w-1/3 flex flex-row items-center justify-center">
                  <div class="absolute w-full h-0.5 bg-gray-400 rounded"></div>
                  <ion-icon class="w-6 h-6 bg-white text-main px-2" name="airplane"></ion-icon>
                </div>
                <div class="w-1/3 flex flex-col items-center">
                  <p class="font-extrabold" id="heure_arrive"></p>
                  <p class="mt-1 text-sm text-gray-700" id="air_arrive"></p>
                </div>
              </div>
              <div class="mt-4 border rounded py-3 flex flex-wrap justify-center items-center">
                <div class="w-1/2 flex flex-col items-center">
                  <p class="text-sm text-gray-700">Date</p>
                  <p class="font-extrabold mt-2 text-sm" id="date_depart"></p>
                </div>
                <div class="w-1/2 flex flex-col items-center">
                  <p class="text-sm text-gray-700">Numéro du vol</p>
                  <p class="font-extrabold mt-2 text-sm" >AC <span id="num_vol"></span></p>
                </div>

              </div>
              <div class="mt-4 py-3 flex flex-wrap justify-center items-center">
                <div class="w-1/2 flex flex-col px-2">
                  <p class="text-sm text-gray-700">Nombre de passagers</p>
                  <%= form.number_field :nombre_passage, :class => "text-sm mt-1 border rounded bg-white px-3 py-2 outline-none w-full", :min => 1, :max => 99, :placeholder => "Nombre de passagers", :required => true, :onkeyup => "input_value(this)", :onchange => "input_value(this)",:id => "input_nombre"%>
                </div>
                <div class="w-1/2 flex flex-col px-2">
                  <p class="text-sm text-gray-700">Choix de la classe</p>
                  <select id="select_place" onchange="value_select(this)" name="class_seat" class="text-sm mt-1 border rounded bg-white px-3 py-2 outline-none w-full">
                    <option value="economique">économique</option>
                    <option value="affaires">affaires</option>
                  </select>
                </div>
                <div class="w-full flex justify-center items-center mt-4">
                  <p class="text-sm text-gray-700"><span id="nombre_place_restante"> </span></p>
                </div>

              </div>
            </div>
            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">

              <div class="w-1/2 flex flex-row-reverse">
                <button type="submit" id="btn_submit_reserver" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-main text-base font-medium text-white hover:bg-main/60 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">Réserver</button>

                <button type="button" @click="isOpen = false" onclick="reset_value()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Annuler</button>
              </div>
              <div class="w-1/2 flex items-center">
                <!--<p class="text-xl"> <span class="font-extrabold">35€</span> / personne</p>-->
              </div>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

app/views/home/showairport.html.erb
<% if notice || alert %>
  <div class="absolute top-6 left-6 z-[99]">
    <div class="p-4 bg-green-600 rounded">
      <p class="text-sm text-white">
        <%= notice %>
        <%= alert %>
      </p>
    </div>
  </div>
<% end %>

<div x-data="{ isOpen: false }">

  <div class="w-full h-screen overflow-hidden">
    <!--<video class="w-full h-full absolute left-0 top-0 object-cover" src="video.mp4" autoplay muted loop type="mp4"></video>-->
    <img class="w-full h-full absolute left-0 top-0 object-cover" src="https://images4.alphacoders.com/241/241776.jpg">

    <%= image_tag("mask.jpg", class: "absolute w-full h-full left-0 top-0 z-1 mix-blend-screen") %>

    <div class="absolute w-full h-full flex justify-center items-center">
      <h1 class="text-[13vw] text-white uppercase font-bold text-shadow">Aircrash</h1>
    </div>

    <div class="absolute top-10 left-20 z-99">
      <%= link_to 'Annuler recherche', "/", :class => "text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
    </div>

    <% if user_signed_in? %>
      <div class="absolute top-10 right-20 z-99 flex flex-row">
        <% if @nombre_reservations_attente > 0 %>
          <div x-data="{ dropdownOpen: false }" class="relative inline-block text-left">
            <div>
              <button type="button" @click="dropdownOpen = ! dropdownOpen" class="relative inline-flex justify-center w-full border-gray-300 px-2 py-2" id="menu-button" aria-expanded="true" aria-haspopup="true">
                <ion-icon class="relative w-5 h-5 text-main" name="notifications-outline">
                </ion-icon>
                <div class="absolute top-2 right-2 bg-red-500 text-sm border rounded-full w-2 h-2"></div>
                <span class="animate-ping absolute inline-flex w-5 h-5 rounded-full bg-main opacity-75"></span>
              </button>
            </div>

            <!--
              Dropdown menu, show/hide based on menu state.

              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <div
              x-show="dropdownOpen"
              x-transition:enter="transition ease-out duration-100"
              x-transition:enter-start="transform opacity-0 scale-95"
              x-transition:enter-end="transform opacity-100 scale-100"
              x-transition:leave="transition ease-in duration-75"
              x-transition:leave-start="transform opacity-100 scale-100"
              x-transition:leave-end="transform opacity-0 scale-95"
              class="origin-center absolute right-0 mt-2 w-96 rounded-md shadow-lg flex justify-center items-center bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
              <p class="text-gray-700 block px-4 py-2 text-sm"><span class="font-extrabold text-main text-base mr-2"><%= @nombre_reservations_attente  %></span> réservations en attentes de confirmations</p>
            </div>
          </div>
        <% end %>
        <%= button_to 'Se déconnecter', destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white" %>
        <%= link_to 'Mes réservations', compte_index_path, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
      </div>
    <% else %>
      <div class="absolute top-10 right-20 z-99 flex flex-row">
        <%= link_to 'Se connecter', new_user_session_path, :data => { :no_turbolink => true }, :class => "text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
        <%= link_to 'S\'inscrire', new_user_registration_path, :data => { :no_turbolink => true }, :class => "ml-3 text-sm border rounded bg-white px-3 py-2 hover:bg-main/50 hover:text-white"%>
      </div>
    <% end %>


    <div class="absolute bottom-10 left-0 w-full">
      <%= form_with :url => "search_airport", method: :get do |form| %>
        <div class="mx-32 bg-slate-100/80 shadow-md h-24 flex flex-wrap justify-center items-center px-6">
          <div class="w-2/5 flex flex-row justify-center items-center px-10">
            <p class="text-sm">Départ</p>
            <%= form.text_field :departure_airport, :class => "text-sm ml-3 border rounded bg-white px-3 py-2 outline-none w-full", :placeholder => "Aéroport Départ" %>
          </div>
          <div class="w-2/5 flex flex-row justify-center items-center px-10">
            <p class="text-sm">Arrivée</p>
            <%= form.text_field :arrival_airport, :class => "text-sm ml-3 border rounded bg-white px-3 py-2 outline-none w-full", :placeholder => "Aéroport Arrivée" %>
          </div>
          <div class="w-1/5 flex flex-col justify-center items-center">
            <%= form.submit "Rechercher", :class => "border rounded bg-main/80 px-3 py-2 hover:bg-main text-white" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-16">
    <div class="relative flex justify-center items-center flex-col">
      <div class="absolute w-11/12 h-2 bg-main z-[1] rounded"></div>
      <h2 class="text-5xl uppercase font-bold text-shadow z-[2] bg-white px-10">Liste de recherche de vols</h2>
    </div>
    <div class="mt-16 flex flex-wrap">
      <% @flights.each do |flight| %>
        <%= render flight %>
      <% end %>
    </div>

    <div class="flex mt-4 mx-16 justify-center items-center">
      <div class="flex flex-row">
        <%= paginate @flights %>
      </div>
    </div>
  </div>


  <footer class="mt-8 bg-main h-32 flex flex-wrap px-24 text-white">
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <a href="#" class="hover:text-gray-300">Conditions générales de transport</a>
      <a class="mt-1 hover:text-gray-300" href="#">Conditions d’utilisation</a>
      <a class="mt-1 hover:text-gray-300" href="#">Politique de confidentialité</a>
    </div>
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <p>2022 © DAWIN B. Tous droits réservés</p>
      <p class="uppercase text-xl font-extrabold mt-1">ra</p>
    </div>
    <div class="w-1/3 flex flex-col text-sm justify-center items-center">
      <a href="#" class="hover:text-gray-300">Cookies</a>
      <a class="mt-1 hover:text-gray-300" href="#">Nous contacter</a>
      <a class="mt-1 hover:text-gray-300" href="#">Préférences en matière de cookies</a>
    </div>
  </footer>

  <div
    x-show="isOpen"
    x-transition:enter="ease-out duration-100"
    x-transition:enter-start="hidden"
    x-transition:enter-end="block"
    x-transition:leave="ease-in duration-100"
    x-transition:leave-start="block"
    x-transition:leave-end="hidden"
    class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">

    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

    <div class="fixed z-10 inset-0 overflow-y-auto">
      <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
        <div
          class="bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-lg sm:w-full">
          <%= form_with :html=> {:id => 'url_form'}, method: :post do |form| %>
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
              <div class="py-3 flex flex-row justify-center">
                <div class="w-1/3 flex flex-col items-center">
                  <p class="font-extrabold" id="heure_depart"></p>
                  <p class="mt-1 text-sm text-gray-700" id="air_depart"></p>
                </div>
                <div class="relative w-1/3 flex flex-row items-center justify-center">
                  <div class="absolute w-full h-0.5 bg-gray-400 rounded"></div>
                  <ion-icon class="w-6 h-6 bg-white text-main px-2" name="airplane"></ion-icon>
                </div>
                <div class="w-1/3 flex flex-col items-center">
                  <p class="font-extrabold" id="heure_arrive"></p>
                  <p class="mt-1 text-sm text-gray-700" id="air_arrive"></p>
                </div>
              </div>
              <div class="mt-4 border rounded py-3 flex flex-wrap justify-center items-center">
                <div class="w-1/2 flex flex-col items-center">
                  <p class="text-sm text-gray-700">Date</p>
                  <p class="font-extrabold mt-2 text-sm" id="date_depart"></p>
                </div>
                <div class="w-1/2 flex flex-col items-center">
                  <p class="text-sm text-gray-700">Numéro du vol</p>
                  <p class="font-extrabold mt-2 text-sm" id="num_vol"></p>
                </div>

              </div>
              <div class="mt-4 py-3 flex flex-wrap justify-center items-center">
                <div class="w-1/2 flex flex-col px-2">
                  <p class="text-sm text-gray-700">Nombre de passagers</p>
                  <%= form.number_field :nombre_passage, :class => "text-sm mt-1 border rounded bg-white px-3 py-2 outline-none w-full", :min => 1, :max => 99, :placeholder => "Nombre de passagers", :required => true, :onkeyup => "input_value(this)", :id => "input_nombre"%>
                </div>
                <div class="w-1/2 flex flex-col px-2">
                  <p class="text-sm text-gray-700">Choix de la classe</p>
                  <select id="select_place" onchange="value_select(this)" name="class_seat" class="text-sm mt-1 border rounded bg-white px-3 py-2 outline-none w-full">
                    <option value="economique">économique</option>
                    <option value="affaires">affaires</option>
                  </select>
                </div>
                <div class="w-full flex justify-center items-center mt-4">
                  <p class="text-sm text-gray-700"><span id="nombre_place_restante"> </span></p>
                </div>

              </div>
            </div>
            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">

              <div class="w-1/2 flex flex-row-reverse">
                <button type="submit" id="btn_submit_reserver" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-main/60 text-base font-medium text-white hover:bg-main focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">Réserver</button>

                <button type="button" @click="isOpen = false" onclick="reset_value()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Annuler</button>
              </div>
              <div class="w-1/2 flex items-center">
                <!--<p class="text-xl"> <span class="font-extrabold">35€</span> / personne</p>-->
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>