config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :flights

  devise_for :users

  post '/reservations/create/:id', to: 'reservations#create'
  get 'search_airport', to: 'home#showairport'

  get 'ajax_show_reservation/index'
  get '/ajax_show_reservation/:id', to: 'ajax_show_reservation#show'
  get '/reservations/delete/:id', to: 'reservations#destroy'
  get 'compte/index'
  get 'home/index'

  get 'reservations/confirmations/:id_billet', to: 'reservations#confirmation'

  get 'qr/:id', to: 'qr#index'


  root to: "home#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  has_one :flight
  has_one :user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  def create

    @random = SecureRandom.alphanumeric(6)

    if Reservation.select('identifiantbillet').where("identifiantbillet = :billet", {billet: @random}).exists?
      @random = SecureRandom.alphanumeric(6)
    end

    @reservation = Reservation.new(:flight_id => params[:id], :user_id => current_user.id, :nombre_passage => params[:nombre_passage], :class_seat => params[:class_seat], :statut => "Valide", :identifiantbillet => @random)


    respond_to do |format|
      if @reservation.save

        @flight = Flight.find(params[:id])
        @user = User.find(current_user.id)
        ReservationMailer.with(user: @user, flight: @flight, reservation: @reservation, billet: @random).welcome_email.deliver_later

        format.html { redirect_to home_index_path, notice: "Un email de récapitulation vous à été envoyé" }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to compte_index_path, notice: "La réservation à été annulée" }
      format.json { head :no_content }
    end
  end

  def confirmation
    @reservation = Reservation.where("identifiantbillet = :billet", {billet: params[:id_billet]}).take

    if @reservation.user_id == current_user.id
        @reservation.update(:statut => "Valide")

        @statut_confirmation = true
        respond_to do |format|
          format.html { render 'reservations/confirmation', notice: "La réservation à bien été validée" }
          format.json { render @statut_confirmation }
        end
    else
        @statut_confirmation = false

        respond_to do |format|
          format.html { render 'reservations/confirmation' }
          format.json { render @statut_confirmation }
        end
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:flight_id, :user_id, :nombre_passage, :class_seat, :statut)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with :html=> {:id => 'url_form'}, method: :post do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.number_field :flight_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :nombre_passage, style: "display: block" %>
    <%= form.number_field :nombre_passage %>
  </div>

  <div>
    <%= form.label :class_seat, style: "display: block" %>
    <%= form.text_field :class_seat %>
  </div>

  <div>
    <%= form.label :statut, style: "display: block" %>
    <%= form.text_field :statut %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>" class="relative flex flex-wrap my-3 mx-16 w-full h-40 border <% if reservation.statut == "en attente" %>border-orange-500 <% end %>shadow rounded-md px-3 py-4 hover:scale-102 ease-linear transition-all duration-150">
  <div class="absolute -left-8 -top-8 text-xl rounded-full w-32 h-16 bg-main text-white font-extrabold shadow flex items-center justify-center"><%= reservation.identifiantbillet %></div>
  <div class="absolute -right-8 -top-8 text-xl w-16 h-16  rounded-full bg-main text-white font-extrabold shadow flex items-center justify-center"><%= reservation.nombre_passage %></div>
  <div class="w-9/12 border-r-2 border-main flex items-center flew-row">
    <div class="w-9/12 flex flex-row justify-center">
      <div class="w-1/3 flex flex-col items-center">
        <p class="font-extrabold"><%= reservation.departure_date.to_datetime.strftime("%H:%M") %></p>
        <p class="mt-2 text-sm text-gray-700"><%= reservation.departure_airport %></p>
      </div>
      <div class="relative w-1/3 flex flex-row items-center justify-center">
        <div class="absolute w-full h-0.5 bg-gray-400 rounded"></div>
        <ion-icon class="w-6 h-6 bg-white text-main px-2" name="airplane"></ion-icon>
        <div class="absolute w-full top-full flex items-center justify-center text-sm text-gray-500">Durée <%= Time.at(reservation.duration).utc.strftime("%M:%S") %></div>
      </div>
      <div class="w-1/3 flex flex-col items-center">
        <p class="font-extrabold"><%= (reservation.departure_date.to_datetime + reservation.duration.minutes).strftime("%H:%M")  %></p>
        <p class="mt-2 text-sm text-gray-700"><%= reservation.arrival_airport %></p>
      </div>
    </div>
    <div class="w-3/12 flex flex-col items-center justify-center">
      <p class="text-sm text-gray-500">Numéro du vol</p>
      <p class="mt-1 font-bold">AC <%= reservation.number %></p>
      <p class="mt-2 text-sm text-gray-500">Classe choisi</p>
      <p class="mt-1 font-bold"><%= reservation.class_seat %></p>
    </div>
  </div>
  <div class="w-3/12 flex flex-col justify-center items-center">
    <p class="mb-5 text-sm"><%= reservation.departure_date.to_datetime.strftime("%d/%m/%Y") %></p>
    <div class="w-full flex justify-center items-center flex-wrap ">
      <div class="w-1/2 flex flex-col justify-center items-center">
        <p class="text-sm text-gray-500"> statut </p>
        <p class="mb-2 font-bold"><%= reservation.statut %></p>
      </div>
      <div class="w-1/2 flex flex-col justify-center items-center">
        <a href="/reservations/delete/<%= reservation.id %>" onclick="return confirm('Etes vous sur de vouloir annuler ?')">
          <button class="border rounded bg-[#FF0000]/80 px-3 py-2 hover:bg-[#FF0000] text-white">Annuler</button>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/reservations/confirmation.html.erb
<div class="w-full h-screen overflow-hidden">
  <!--<video class="w-full h-full absolute left-0 top-0 object-cover" src="video.mp4" autoplay muted loop type="mp4"></video>-->
  <img class="w-full h-full absolute left-0 top-0 object-cover" src="https://images4.alphacoders.com/241/241776.jpg">

  <%= image_tag("mask.jpg", class: "absolute w-full h-full left-0 top-0 z-1 mix-blend-screen") %>

  <div class="absolute w-full h-full flex justify-center items-center">
      <div class="bg-white w-[500px] pt-12 pb-6 px-10 flex justify-center items-center flex-col rounded-xl shadow-lg">
        <% if @statut_confirmation %>
          <div class="flex items-center justify-center text-center">
            Votre réservation à bien été confirmé au sein de notre agence
          </div>
          <div class="mt-3 flex items-center justify-center text-center">
            Vous avez jusqu'à 24h avant l'heure de départ pour annuler
          </div>

          <%= link_to 'Retour au site', "/", :class => "mt-4 text-sm border rounded bg-main px-3 py-2 hover:bg-main/50 text-white"%>
        <% else %>
            <div class="flex items-center justify-center text-center flex-col">
              Cette réservation ne correspond pas à votre compte
              <%= button_to 'Se déconnecter', destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, :class => "mt-6 text-sm border rounded bg-main px-3 py-2 hover:bg-main/50 text-white" %>
            </div>
          <% end %>
      </div>

  </div>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>